service: bnti

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - src/functions/**

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-functions-base-path

custom:
  functionsBasePath: src/functions
  serverless-offline:
    port: 3001
