service: bnti

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - functions/**

functions:
  hello:
    handler: functions/index.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

custom:
  serverless-offline:
    port: 3001
